name: "Publish"
on:
  push:
    branches:
      - master
jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn build
      - uses: copapow/version-bump-package@v1
        with:
          patch_label: version-patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'Bump package version'
      - run: yarn publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}