name: "Publish"
on:
  push:
    branches:
      - master
jobs:
  release:
    name: "Release"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn build
      - run: yarn version --patch --no-git-tag-version
      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'Bump package version'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}